### ISSUE TITLE
Develop Tassled Cap (wetness) Styles

### ISSUE THREAD

**Issue by whatnick** [GeoscienceAustralia/dea-config#613] opened 2020-10-29 04:51 UTC
Tasselled Cap Wetness Percentiles OWS Configuration and Styles.

**Comment by vnewey** [comment] 2020-10-30 05:07
I have put in a ows layer request, but here are some additional details.

DEA Wetness Percentiles (Landsat)
Datacube product name : ga_ls_tcw_percentiles_2

For indexing:
the product definition is here:
dea-config/products/ga_ls_tcw_percentiles_2/ga_ls_tcw_percentiles_2.yaml

the cogs are here:
https://data.dea.ga.gov.au/?prefix=derivative/ga_ls_tcw_percentiles_2/
s3://dea-public-data/derivative/ga_ls_tcw_percentiles_2
CMI record: https://cmi.ga.gov.au/data-products/dea/337/dea-wetness-percentiles-landsat

TCW symbology in matplotlib:
cmap = gist_earth_r   
min value =  -1200  
max value= 0

In the ga_ls_tcw_percentiles_2 product there are 3 bands TCW_PC_10, TCW_PC_50, TCW_PC_90

We would like a layer for each band. Same description and symbology for each.

**Comment by pindge** [comment] 2020-11-22 22:42
Duplicate of #618

**Closed** 2021-01-18 06:46 UTC
Labels: enhancement
